name: monitoring
services:
  portainer:
    image: portainer/portainer-ce:sts
    container_name: portainer
    restart: unless-stopped
    ports:
      - "192.168.50.11:9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "192.168.50.11:3001:3001"
    volumes:
      - uptime_kuma_data:/app/data

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: host
    ports:
      - "192.168.50.11:61208:61208"
    environment:
      GLANCES_OPT: -w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro

volumes:
  portainer_data:
  uptime_kuma_data:
